groups:
  - name: basic-alerts
    rules:
      - alert: HighCPUUsage
        expr: process_cpu_seconds_total > 90
        for: 1m
        labels:
          severity: warning
        annotations:
          description: "CPU kullanımı çok yüksek"
